「サーバを作ろう！」のページを追加
y-tac-d/tech_learn_docs pull request #1
Opened 2021-10-22 10:26 UTC by takarada

「サーバを作ろう！」のページを追加しました。

当該ページには
・AWSコンソールを開いてEC2のインスタンスを立てる手順
・作ったインスタンスにSSH接続させる手順
・インスタンスにnginxをインストールする手順
を記載しています。

2021-10-26 03:30 UTC, y-tac-d requested changes
確認しました！修正をお願いします！

2021-10-26 03:30 UTC, y-tac-d commented on handson/server/aws_ec2/server_1.md
> +
@takarada  リージョンを選ぶ手順を追加して、"ハンズオンで利用するリージョン”も指定してあげてください。東京でいいとはおもう

2021-10-26 03:30 UTC, y-tac-d commented on handson/server/aws_ec2/server_1.md
> +この時、ソースのところに「0.0.0.0/0」と表記されています。
自身の接続IPの確認手順と修正例を記述してください（多分ソースIPの取得方法がわかんない人いるとおもう）

2021-10-26 03:30 UTC, y-tac-d commented on handson/server/aws_ec2/server_1.md
> +ブラウザからhttpで作成したインスタンスにアクセスすれば、以下画面が表示されます。
ブラウザからHTTPアクセスするやり方を記述してください

2021-11-10 09:11 UTC, y-tac-d commented on handson/server/aws_ec2/server_1.md
> +ブラウザからhttpで作成したインスタンスにアクセスすれば、以下画面が表示されます。
修正確認しました、がEC2の自動ドメイン経由で確認する方法も追記をお願いします！

2022-01-04 07:11 UTC, takarada commented
@y-tac-d 
確認ありがとうございます。
以下修正を施しました、ご確認くださいませー

    ・インスタンスにアクセスする手法をSSHクライアントから、AWS Session Managerを使った方法に変更
    ・ブラウザでアクセスする手法にEC2の自動ドメイン経由で確認する方法を追記
    ・マークダウンのリンクの書き方を統一
    ・その他文言の微修正

2022-02-25 05:01 UTC, y-tac-d commented
良さそうなので一度マージします

2022-02-25 05:01 UTC, merged